export const shop = [
  'skincare',
  'fragrances',
  "men's clothing",
  'jewelery',
  'electronics',
  "women's clothing",
  'smartphones',
  'laptops',
  'groceries',
  'home-decoration',
  'furniture',
  'tops',
  'womens-dresses',
  'womens-shoes',
  'mens-shirts',
  'mens-shoes',
  'mens-watches',
  'womens-watches',
  'womens-bags',
  'womens-jewellery',
  'sunglasses',
  'automotive',
  'motorcycle',
  'lighting',
  'brands',
  'Sandisk',
  'Apple',
  'Naya combo',
];
export const support = ['Help', 'Track order', 'Shipping', 'Returns'];
export const company = ['About', 'Blog', 'Services', 'Contact us'];
